server:
  port: 8123
  address: 0.0.0.0  # 允许外部访问
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        name: SESSION_APP4
        max-age: 2592000
spring:
  application:
    name: demo-picture-backend
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_picture
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 4
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  # Session 配置
  session:
    store-type: redis
    # session 30 天后过期
    timeout: 2592000
    # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: local

mybatis-plus:
  configuration:
    # MyBatis 配置, 驼峰命名
    map-underscore-to-camel-case: false
    # MyBatis 配置, 打印 SQL仅在开发中打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #逻辑删除
  global-config:
    db-config:
      logic-delete-field: isDeleted # 逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.ouguofeng.controller


# 自己的腾讯云cos对象存储配置
cos:
  client:
    host: xxxxxxxxxxxxxxxxxxxxx
    secretId: xxxxxxxxxxxxxxxxxxxxx
    secretKey: xxxxxxxxxxxxxxxxxxxxx
    region: xxxxxxxxxxxxxxxxxxxxx
    bucket: xxxxxxxxxxxxxxxxxxxxx

## 阿里云 AI 配置
aliYunAi:
  apiKey: xxxxxxxxxxxxxxxxxxxxx